defaults: &defaults
  docker:
    - image: circleci/node:8

  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      # lint
      - run: npm run lint

      # upload coverage to codecov.io
      - run: npm run codecov

  publish_docs:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - add_ssh_keys

      - run npm run publish-docs

workflows:
  version: 2
  build_and_publish_docs:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - publish_docs:
          requires:
            - build
          filters:
            branches:
              only:
                - master
